name: Tests
'on': [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - run: docker build --tag webproj .
      - run: 'docker run -d -p 80:80 --name restapi webproj'
      - run: docker ps
      - run: sudo apt-get update

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
            environment-file: environment-dev.yaml
            auto-activate-base: false
            activate-environment: webproj
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Pytest
        run: pytest --cov

      - run: curl -s localhost/v1.0/trans/EPSG:4258/DK:S34S/55.0,12.0 > S34S.out

      - run: echo >> S34S.out # Add's a \n at the end of the file. This satifies the diff further down.
      - run: cat S34S.out
      - run: diff test_s34s.out S34S.out
